Revert "Fix DNS service default option value handling (#618)"
This reverts commit 07bbd49b88d520f4a12769f293e7daaecda0bc6c.

diff --git a/tailscale/rootfs/etc/s6-overlay/s6-rc.d/init-magicdns-proxies-upstream-list/run b/tailscale/rootfs/etc/s6-overlay/s6-rc.d/init-magicdns-proxies-upstream-list/run
--- a/tailscale/rootfs/etc/s6-overlay/s6-rc.d/init-magicdns-proxies-upstream-list/run
+++ b/tailscale/rootfs/etc/s6-overlay/s6-rc.d/init-magicdns-proxies-upstream-list/run
@@ -27,14 +27,11 @@ declare tailnet
 if ! bashio::config.has_value "accept_dns" || \
   bashio::config.true "accept_dns"
 then
-  # Get login_server if configured
-  if bashio::config.has_value "login_server"; then
-    # We have to be able to determine login_server from this address
-    if ! login_server=$(awk -F[/:] '{print $4}' <<<"$(bashio::config "login_server")") || \
-      ! bashio::var.has_value "${login_server}"
-    then
-      bashio::exit.nok "Determining host name from '$(bashio::config "login_server")' has failed"
-    fi
+  # We have to be able to determine login_server from this address
+  if ! login_server=$(awk -F[/:] '{print $4}' <<<"$(bashio::config "login_server")") || \
+    ! bashio::var.has_value "${login_server}"
+  then
+    bashio::exit.nok "Determining host name from '$(bashio::config "login_server")' has failed"
   fi
   black_white_list+=("${login_server}")
 
